# Generated by Django 4.2.7 on 2024-01-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=99, unique=True)),
                ('definition', models.TextField(blank=True, max_length=333, null=True, unique=True)),
                ('translation', models.CharField(max_length=99, unique=True)),
                ('translated_definition', models.TextField(blank=True, max_length=333, null=True, unique=True)),
            ],
            options={
                'ordering': ('-word',),
            },
        ),
    ]
